baseURL = '/'
languageCode = 'en-us'
title = 'Sourcery Zone'
theme = 'sourcery'

# How dates are formattted
defaultContentLanguage = "en-us"

enableEmoji = true
ignoreErrors = ["additional-script-loading-error"] # ignore error of loading additional scripts.


[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 1
[[menu.main]]
  name = 'Articles'
  url = '/articles'
  weight = 3
[[menu.main]]
  name = 'About'
  url = '/about'
  weight = 4
# [[menu.main]]
#   name = 'Stack'
#   url = '/stack'
#   weight = 5
# [[menu.main]]
#   name = 'Links'
#   params.header = true
#   weight = 6
# [[menu.main]]
#   name = 'Polywork'
#   url = 'https://polywork.com'
#   weight = 7

# Allow to override `browserconfig.xml` params (configuration for windows embedded browsers)
[params.browserconfig]
  TileColor = "#2d89ef" # default windows 10 blue tile color

[[params.socialIcons]]
name = "github"
url = "https://github.com/sourcery-zone"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/sourcery_zone"

[[params.socialIcons]]
name = "Rss"
url = "/index.xml"

# syntax highlight settings
[markup]
  [markup.highlight]
    noClasses = false
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
	[markup.tableOfContents]
		startLevel = 2 # ToC starts from H2
		endLevel = 4 # ToC ends at H4
		ordered = false # generates <ul> instead of <ol>

[Languages.en-us.params]
  sitename = "Sourcery Zone"
  defaultColor = "auto" # set color mode: dark, light, auto
  # Setting it to 'auto' applies the color scheme based on the
  # visitor's device color preference.If you don't specify anything,
  # ignore this parameter, or leave it blank, the default value is set
  # to 'auto'.  You can take a look at layouts/index.html for more
  # information.
  description = "This persona is a personal project to traverse the intersection of AI, Robotics and Cybersecurity as a software engineer."
  mainSections = ['articles']
  toc = true # set to false to disable table of contents 'globally'
  tocOpen = false # set to true to open table of contents by default
  goToTop = true # set to false to disable 'go to top' button
  additionalScripts = ['js/custom.js', 'js/custom-2.js']
  # Will try to load 'assets/js/custom.js' and 'assets/js/custom-2.js'.
  # Your custom scripts will be concatenated to one file `custom.js`.
  # When building for production it will be minified.
  # The file `custom.js` is loaded on each page (before body tag ends).
  dateFormat = "" # date format used to show dates on various pages. If nothing is specified, then "2 Jan 2006" format is used.
  # See https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference for available date formats.
  rssFeedDescription = "summary" # available options: 1) summary 2) full
  # summary - includes a short summary of the blog post in the RSS feed. Generated using Hugo .Summary .
  # full - includes full blog post in the RSS feed. Generated using Hugo .Content .
  # By default (or if nothing is specified), summary is used.

[Languages.en-us.params.author]
  avatar = "avatar.png" # put the file in assets folder; also ensure that image has same height and width
  # Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
  intro = "Sourcery Zone"
  name = "The Operator"
  description = "This persona is a personal project to traverse the intersection of AI, Robotics and Cybersecurity as a software engineer."

# Allow to override webmanifest options
[Languages.en-us.params.webmanifest]
  name = "Sourcery Zone" # will use "params.sitename" or "title" by default
  short_name = "Sourcery Zone" # same as name
  start_url = "/" # will use homepage url by default
  theme_color = "#434648" # default is "#434648" (base color of text). Also will override html `<meta name="theme-color" />`
  background_color = "#fff" # by default depend on "params.defaultColor" for "light" or "auto" will be set to "#fff" for dark will be "#131418" (color of dark mode background)
  display = "standalone"
