:PROPERTIES:
:ID:       18f7db62-1bed-44cb-a09f-f99cfed683dc
:END:
#+title: Culture of Software Industry
#+date: 2025-02-17T06:27:08+01:00
#+hugo_draft: true
#+hugo_auto_set_lastmod: t

Intention: Knowing the flaws of human interaction and ambition in
today's software industry, and how it hurts the culture.

There are many aspects of the software development industry that needs
to be improved, and that's why there are so much room for
innovation. What I'm interested in today though, is somewhat
different: The human factor!

A software development consultancy is charging its client for about a
million euros, to develop a 3 component MVP of a mobile and web
application in a time span of 6 months. The scope of the challenge
though is so simple, that I have an estimate of accomplishing it in 3
weeks! There is no authentication, user management, subscription, and
many other generic functionality in need of development, and it's just
a matter of integrating it with existing solutions used in other
applications for the client.

Consultancy companies and even internal engineers, go to an extend of
dehumanizing each other, with only one intention, to win a bigger
portion of the cake, or getting promoted.

Talents need to develop skills to generate bullshit in fancy slides to
influence either companies, managers, HR, ... to give them an
opportunity, and that's an accepted norm.

The first time I read about considering software development a social
activity was in the Your Code as a Crime Scene book. Obvious fact like
many other activities done by humans as social species. However, this
human/social factor could also harm the activity, if it is not
controlled or becomes toxic.

There are so much hype and excitement in the industry for a glimpse of
hope to not need any more software engineers. The hope is for AI to
get smart enough to solve any problems, software engineers were
educated and tasked to solve, with a dismal fraction of cost. At this
stage, I don't much care about such a hope being solid or not. What I
care about is the intention.

Why the industry has lost so much trust in engineers? The thing is,
like any other sick system, you can't point your finger towards one
aspect of it and hoping to fix it will fix it all.

Just like a sick government, given enough time, one problematic
aspect, like mismanagement, or bulshit presentation as norm, will
initiate a cycle of corrupt. The cycle will generate a corrupted
feedback loop, and eventually involve anyone in the system to be part
of the problem, one way or another. It'd become so difficult after a
while to brave it out, and fight against the issue.

We see a lot of such signs recently. From technical decisions listed
in [[https://antirez.com/news/145][We are destroying software]], to open source dramas happening all
over the industry, shows one clear fact: We've lost mutual
understanding, and nurtured a culture of mistrust and fake
competition. Software or computer industry is not nurturing innovation
for the sake of advancement, but only repeating itself to gain more
power and profit. That's what corrupts everything.

